{% set setup_data = load_setup_py_data() %}
package:
  name: get-biomes
  version: {{ setup_data['version'] }}

source:
  git_rev: {{ setup_data['version'] }}
  git_url: https://github.com/genomewalker/get-biomes.git

build:
  number: 0
  skip: true  # [win and py27 or win32]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python==3.9
    - setuptools
    - pip
    - Cython>=0.29.24
  run:
    - python==3.9
    - pandas>=1.3.3
    - tqdm
    - requests>=2.28.1
test:
  commands:
    - getBiomes -h

about:
  home: https://github.com/genomewalker/get-biomes
  summary: "A simple tool to get biomes related data from MGnify and ENA"
  license: {{ setup_data['license'] }}
  license_file: LICENSE
