name: getBiomes_ci

on: [push, pull_request]

jobs:
  getBiomes_ci:
    name: getBiomes_ci
    runs-on: "ubuntu-latest"
    if: "!contains(github.event.head_commit.message, '[skip_ci]')"
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          channel-priority: true
          environment-file: environment.yml
          activate-environment: getBiomes
      - name: Lint with flake8
        shell: bash -l {0}
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pip install Cython 'ray>=0.8.7'
          pip install -e .
          pip install pytest pytest-cov pytest-dependency pytest-console-scripts
      - name: Check getBiomes help message
        shell: bash -l {0}
        run: |
          getBiomes --help
